url: 'https://danieljmwilliams.github.io'
baseurl: '/CheffingItUp'
title: 'Paulina Eats'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

collections:
  recipes:
    output: true
    permalink: /recipes/:title/


exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
